# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70bcec668ca98949515f4b6cae1dc3d19d7fdb046713902f17ed996b2629549261478e05120eb5ed499dfe1c1a2bd84df9f0c4e242d5465e73e46b9458320a63

test:
  secret_key_base: dbe67911e253646b88c80cad723c1f7f2442c7995b4e1443ddb2e1df7f7538c190d04fb6909efcb5185f847343196fb0f68cf6261b3a30bf0b81f3e9299266a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
